BASE: ['']
TOOLBOX_MODE: "train_and_test" # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 200
  LR: 1e-5
  MODEL_FILE_NAME: CogPhys_rPPG_ch3_PhysNet
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 15
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    EXP_DATA_NAME: "ta_cp+_combined_loss"
    FOLD:
      FOLD_NAME: 'fold_0' # Due to the way config is coded, this is used a substitute for FOLD_NUM
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['thermal_below']
      LABEL: ['respiration']
      INPUT_TYPE: [['Downsample', 'NormAndFloat']]
      LABEL_TYPE: [['Downsample', "Standardize"]]
      INPUT_FS: [60]
      LABEL_FS: [30]
      SEQ_LENGTH: 300
      RET_DICT: False
VALID:
  DATA:
    FS: 15
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    EXP_DATA_NAME: "ta_cp+_combined_loss"
    FOLD:
      FOLD_NAME: 'fold_0'
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['thermal_below']
      LABEL: ['respiration']
      INPUT_TYPE: [['Downsample', 'NormAndFloat']]
      LABEL_TYPE: [['Downsample', "Standardize"]]
      INPUT_FS: [60]
      LABEL_FS: [30]
      SEQ_LENGTH: 300
      RET_DICT: False
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False                   # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 15
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    EXP_DATA_NAME: "ta_cp+_combined_loss"
    FOLD:
      FOLD_NAME: 'fold_0' # Due to the way config is coded, this is used a substitute for FOLD_NUM
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['thermal_below']
      LABEL: ['respiration']
      INPUT_TYPE: [['Downsample', 'NormAndFloat']]
      LABEL_TYPE: [['Downsample', "Standardize"]]
      INPUT_FS: [60]
      LABEL_FS: [30]
      SEQ_LENGTH: 300
      RET_DICT: False
    FILTERING:
      USE_EXCLUSION_LIST: True
      EXCLUSION_LIST: ['s3_T1', 's8_T1', 's9_T1', 's26_T1', 's28_T1', 's30_T1', 's31_T1', 's32_T1']
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  TYPE: RR
  DROP_RATE: 0.2
  NAME: ContrastPhys
  CONTRASTPHYS:
    FRAME_NUM: 300
    S: 1
    CHANNELS: 3
INFERENCE:
  BATCH_SIZE: 2
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 10        # In seconds
  MODEL_PATH: ""
