BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 50
  LR: 1e-4
  MODEL_FILE_NAME: CogPhys_rPPG_ch3_PhysFormer
  #MODEL_FILE_NAME: CogPhys_rPPG_ch1_PhysFormer
  PLOT_LOSSES_AND_LR: True
  DATA:
    FS: 30
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    DATA_TYPE: "RGB"
    #DATA_TYPE: "NIR"
    EXP_DATA_NAME: "RGB_PhysFormer"
    #EXP_DATA_NAME: "NIR_PhysFormer"
    FOLD:
      FOLD_NAME: 'fold_0' # Due to the way config is coded, this is used a substitute for FOLD_NUM
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['rgb_left']
      #INPUT: ['nir']
      LABEL: ['ppg']
      INPUT_TYPE: [['NormAndFloat']]
      LABEL_TYPE: [['Standardize', 'Downsample']]
      INPUT_FS: [30]
      LABEL_FS: [60]
      SEQ_LENGTH: 300
      H_SIZE: 128
      W_SIZE: 128
      RET_DICT: False
VALID:
  DATA:
    FS: 30
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    #DATA_TYPE: "RGB"
    DATA_TYPE: "NIR"
    EXP_DATA_NAME: "RGB_PhysFormer"
    #EXP_DATA_NAME: "NIR_PhysFormer"
    FOLD:
      FOLD_NAME: 'fold_0'
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['rgb_left']
      #INPUT: ['nir']
      LABEL: ['ppg']
      INPUT_TYPE: [['NormAndFloat']]
      LABEL_TYPE: [['Standardize', 'Downsample']]
      INPUT_FS: [30]
      LABEL_FS: [60]
      SEQ_LENGTH: 300
      RET_DICT: False
TEST:
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR', 'BA']
  USE_LAST_EPOCH: False                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: CogPhys
    DATA_FORMAT: NCDHW
    DATA_PATH: "/shared/ab227/CogPhys/chunked_dataset"
    CACHED_PATH: ""
    #DATA_TYPE: "RGB"
    DATA_TYPE: "NIR"
    EXP_DATA_NAME: "RGB_PhysFormer"
    #EXP_DATA_NAME: "NIR_PhysFormer"
    FOLD:
      FOLD_NAME: 'fold_0' # Due to the way config is coded, this is used a substitute for FOLD_NUM
      FOLD_PATH: './dataset/CogPhysFolds/CogPhys_all_Folds.pkl'
    COGPHYS:
      INPUT: ['rgb_left']
      #INPUT: ['nir']
      LABEL: ['ppg']
      INPUT_TYPE: [['NormAndFloat']]
      LABEL_TYPE: [['Standardize', 'Downsample']]
      INPUT_FS: [30]
      LABEL_FS: [60]
      SEQ_LENGTH: 300
      RET_DICT: False
    FILTERING:
      USE_EXCLUSION_LIST: True
      EXCLUSION_LIST: ['s3_T1', 's8_T1', 's9_T1', 's26_T1', 's28_T1', 's30_T1', 's31_T1', 's32_T1']
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  TYPE: HR
  DROP_RATE: 0.1
  NAME: PhysFormer
  PHYSFORMER:                     # Probably need to update these in some meaningful way
    PATCH_SIZE: 4
    DIM: 96
    FF_DIM: 144
    NUM_HEADS: 4
    NUM_LAYERS: 12
    THETA: 0.7
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        # Change this if you'd like an evaluation window smaller than the test video length
    WINDOW_SIZE: 30        # In seconds
  MODEL_PATH:   ""
